config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "hunters#login", as: "login"
  post "/login", to: "hunters#create_login_session", as: "create_login_session"
  delete "hunters/logout", to: "hunters#logout", as: "logout"
  post "hunter_contracts/new/:contract_id", to: "hunter_contracts#create", as: "hunter_contract_create"
  
  root 'hunter_contracts#index'
  resources :contracts
  resources :hunter_contracts, except: [:new]
  resources :hunters

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
    has_one :HunterContract
    has_many :hunters, through: :HunterContract

    def bounty_info
        "#{self.name}. Value: #{self.BountyAmount}"
    end
end

app/models/hunter.rb
class Hunter < ApplicationRecord
    has_many :HunterContracts, :dependent => :destroy
    has_many :contracts, through: :HunterContracts

    validates :name, uniqueness: true
    validates :name, presence: true
    # validates :password, presence: true

    has_secure_password


end

app/models/hunter_contract.rb
class HunterContract < ApplicationRecord
    belongs_to :contract
    belongs_to :hunter
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_hunter
    before_action :authorize

    private
    
    def current_hunter
        @logged_in_hunter = Hunter.find_by(id: session[:hunter_id])
    end

    def authorize
        if @logged_in_hunter
            #proceeds as normal
        else
            flash[:error] = ["Access Denied. Login to proceed."]

            redirect_to login_path
        end
    end
end


# There is an issue here when hosting to a website here where hunter_id is notdefined as a relation

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    before_action :find_contract, only: [:show]

    def index
    @contracts = Contract.all
    end

    def show
    end
    
    private

    def find_contract
        @contract = Contract.find(params[:id])
    end
end

app/controllers/hunter_contracts_controller.rb
class HunterContractsController < ApplicationController
    before_action :find_hunter_contract, only: [:destroy]
    skip_before_action :authorize

    def new 

    end

    def create
        hunter = HunterContract.create(hunter_id: @logged_in_hunter.id, contract_id: params[:contract_id])
        # @hunter_contract = HunterContract.create(hunter_contract_params)
        redirect_to contract_path(hunter.contract_id)
    end

    def destroy
        find_hunter_contract.destroy
        #byebug
        redirect_to hunter_path(@logged_in_hunter.id)
    end

    def index
        @hunter_contracts = HunterContract.all
        # 30.times list last method? so it always grabs latest bounty hunter to be added onto hunter_contract.all? 
        # then just interpolate hunter and contract name onto string
    end

    private
    
    def find_hunter_contract
        @hunter_contract = HunterContract.find(params[:id])
    end

    def hunter_contract_params
        params.require(:hunter_contract).permit(:hunter_id, :contract_id)
    end
end

app/controllers/hunters_controller.rb
class HuntersController < ApplicationController
    before_action :find_hunter, only: [:show, :edit, :update, :destroy, :login_form]
    skip_before_action :authorize, only: [:new, :create, :login, :create_login_session]
    # skip_before_action :authorize
    
    
    def new
    @hunter = Hunter.new
    end

    def create
    @hunter = Hunter.create(hunter_params)
    if @hunter.valid?
        session[:hunter_id] = @hunter.id
        redirect_to hunter_path(@hunter.id)
    else
        flash[:errors] = @hunter.errors.full_messages
        redirect_to new_hunter_path
    end
    end

    def login
        # render :login
    end

    def create_login_session
        hunter = Hunter.find_by(name: params[:session][:name])
        if hunter && hunter.authenticate(params[:session][:password])
            session[:hunter_id] = hunter.id
            redirect_to hunter_path(hunter.id)
        else
            flash[:errors] = ["That login information is not correct"]
            redirect_to login_path
        end
    end

    def logout
        session[:hunter_id] = nil
        redirect_to hunter_contracts_path
    end
    
    def edit
    end

    def show
    end

    def update
        @hunter.update(hunter_params)
         redirect_to hunter_path(@hunter)

    end

    def destroy
        find_hunter.destroy
        redirect_to new_hunter_path
    end

    private

    def find_hunter
    @hunter = Hunter.find(params[:id])
    end

    def hunter_params
        params.require(:hunter).permit(:name, :planet, :species, :quote, :image_url, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/hunter_contracts_helper.rb
module HunterContractsHelper
end

app/helpers/hunters_helper.rb
module HuntersHelper
end

app/views/contracts/index.html.erb
<h1>Bounty Board</h1>

<% @contracts.each do |contracts| %>
<h4>
    Name of Target: <%= link_to contracts.name, contract_path(contracts.id), {class:'contractName'}%>. 
    Posted by <span class="drafter"><%=contracts.drafter%></span>. 
    Bounty Reward: <span class=bountyAmount><%=contracts.BountyAmount%></span> Republic credits.
</h4>
<hr>
<%end%>

app/views/contracts/show.html.erb
<h1> Official Posting of the Bounty Guild </h1>
<h3> By the authority of the New Republic, this contract is deemed open and legal as released from the Bounty Hunters' Guild. The drafter of this contract, <%= @contract.drafter %> has posted a reward in the amount of <%= @contract.BountyAmount %> against <%= @contract.name %>. This contract is open to members of the Bounty Hunters' Guild to sign and execute.</h3>

<h2> Target Information </h2>
<%= image_tag("#{@contract.image_url}", :alt => "#{@contract.name}") %>
<ul>Name: <%=@contract.name%></ul>
<ul>Species: <%=@contract.species%></ul>
<ul>Last seen: <%=@contract.last_seen%></ul>

<% if @logged_in_hunter.contracts.ids.find_index(@contract.id) %>
<h3> You have already accepted this contract </h3><br>
<%else%>
<%= button_to 'Sign up for this bounty', hunter_contract_create_path(@contract.id) %><br>
<%end%>

<h2>This contract currently has the following signors:</h2>
<h2><% @contract.hunters.uniq.each do |hunter| %>
<%= link_to hunter.name, hunter_path(hunter.id) %> 
<% if hunter.name == @logged_in_hunter.name %>
<%= button_to 'Abandon Contract', hunter_contract_path(hunter.HunterContracts.ids), method: :delete, confirm: "Are you sure you want to abandon this contract?" %><br>
<% end %>
<hr>
<%end%>

app/views/hunter_contracts/index.html.erb
<h1>Bounty Activity</h1>

<div id="container-of-box">
    <% HunterContract.last(25).reverse.each do |list| %>
<%# <div id="box"> %>

    <ul id="ul_box">
        <li class="ul_li">
        <%= link_to list.hunter.name, hunter_path(list.hunter.id), {class:'hunterName'} %>
         has accepted a contract in the amount of 
         <span class= bountyAmount><%=list.contract.BountyAmount %></span>
         against 
        <%= link_to list.contract.name, contract_path(list.contract.id), {class:'contractName'} %>
        </li>
    </ul>

<% end %>
</div>

app/views/hunters/_form.html.erb
<div class=form>
<%= form_for @hunter do |f| %>
  <li class= form_li><%= f.label 'name' %>
  <%= f.text_field :name %></li>
  <li class= form_li><%= f.label 'password' %>
  <%= f.password_field :password %></li>
  <li class= form_li><%= f.label 'planet' %>
  <%= f.text_field :planet %></li>
  <li class= form_li><%= f.label 'species' %>
  <%= f.text_field :species %></li>
  <li class= form_li><%= f.label 'quote' %>
  <%= f.text_field :quote %></li>
  <li class= form_li><%= f.label 'image_url'%>
  <%= f.text_field :image_url %> </li>
  <li class= form_li><%= f.submit %></li>
<% end %>
</div>

app/views/hunters/edit.html.erb
<h1>edit a hunter</h1>
<%=render 'form'%>
<%# <%= button_to 'Delete Yourself', hunter_path(@hunter), method: :delete %> 

app/views/hunters/login.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do|error| %>
        <%= error %>
    <%end%>
<%end%>

<div class=login>
  <h1>Log-In as a hunter</h1>
  <div class=form>
    <%= form_for :session, url: create_login_session_path do |f| %>
      <%= f.label 'name' %>
      <%= f.text_field :name %>
      <%= f.label 'password' %>
      <%= f.password_field :password %>
      <%= f.submit %>
      <% end %>
  </div>
</div>

app/views/hunters/new.html.erb
<% if flash[:errors] %>
<% flash[:errors].each do|error| %>
<%= error %>
<%end%>
<%end%>


<h1>Create a new hunter</h1>
<div class=form>
<%= render 'form'%>
</div>

app/views/hunters/show.html.erb
<h1> Hunter stats:</h1>
<div>
<div class="bio">
<span class=imga><%= image_tag("#{@hunter.image_url}", :alt => "#{@hunter.name}") %></span>

    <div class='info'>
        Name:  <span class=hunterName> <%= @hunter.name %> </span> <br>
        Quote: <%= @hunter.quote%><br>
        Planet: <%= @hunter.planet%><br>
        Species: <%= @hunter.species%><br>
        Number of contracts completed: <span style=color:gold><%= @hunter.contracts_completed%></span><br>
        Number of contracts failed: <span style=color:red><%= @hunter.contracts_failed%></span>
    </div>



<div class='contracts'>
    <h4>Contracts accepted by this hunter:<h4>
    <ul>
        <% @hunter.contracts.reverse.each do |contractslist| %>
        <%#byebug%>
       <li> <%= link_to contractslist.name, contract_path(contractslist.id) %>, Value: <%= contractslist.BountyAmount %></li>
        <br>
        <%end%>
    </ul>
 </div>


<div class='fueding'>
    <h5>This Hunter is feuding with:</h5>
    <% @hunter.contracts.uniq.each do |feud| %>
    <% feud.hunters.uniq.each do |huntername| %>
    <% if @hunter.name != huntername.name %>
    <%= link_to huntername.name, hunter_path(huntername.id) %><br>
    <%end%>
    <%end%>
    <%end%>
</div>

</div>
<div class="buttons">
<% if @logged_in_hunter == @hunter%>
<%= button_to 'Edit your hunter profile', edit_hunter_path(@hunter), method: :get%> 
<%= button_to 'Leave the Guild', hunter_path(@hunter), method: :delete %><br>
<%else%>
<%end%>




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarWarsBounty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <link href="https://fonts.googleapis.com/css?family=Share+Tech+Mono&display=swap" rel="stylesheet"> %>
    <link href="https://fonts.googleapis.com/css?family=Orbitron&display=swap" rel="stylesheet">
  </head>

  <body>
  <div>
    <ul>
        <li><%= link_to 'Bounty List', contracts_path %></li>
        <li><%= link_to 'Bounty Activity', root_path %></li>
        <% if @logged_in_hunter %>
        <li><%= link_to 'Log-Out', logout_path, :method => 'delete' %></li>
        <li>Welcome, <%= link_to @logged_in_hunter.name, hunter_path(@logged_in_hunter.id) %></li>
        <%# link_to huntername.name, hunter_path(huntername.id) %>
        <%else%>
        <li><%= link_to 'Sign-Up', new_hunter_path %></li>
        <li><%= link_to 'Log-In', login_path %></li>
        <%end%>
    </ul>
  </div>
    <%= yield %>
  </body>
</html>